jobs:
  workflow:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./run/main

name: Workflow

on:
  schedule:
    - cron: "0 0/3 * * *"
